version: '3.7'

services:
  mysql:
    container_name: bs_api_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sanctuary_bs
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - bs_api_network

networks:
  bs_api_network: